### ISSUE TITLE
The vertebral labeling doesn’t work for several subject sessions

### ISSUE THREAD

**Issue by Mathilde-16** [Mathilde-16/STOP_MS_data#6] opened 2024-05-29 16:16 UTC
As you would expect, the vertebral labeling doesn’t work for several subject sessions : when I run the sct_label_vertebrae command, almost all subjects have sessions with missing labeled file. Therefore, could we use the SPINEPS method you mentioned ? Or the manual labeling using the sct_label_utils command ?

Below the log file of a subject session without labeled file in output, maybe this will help you to understand
[Script_TEST_9_sub-Control02_ses-aera01.log](https://github.com/Mathilde-16/STOP_MS_data/files/15487415/Script_TEST_9_sub-Control02_ses-aera01.log)

**Comment by jcohenadad** [comment] 2024-05-29 16:46
the log file is not helpful-- what would be helpful is a zipped QC report showing the vertebral labeling ran on the subjects

**Comment by Mathilde-16** [comment] 2024-05-31 17:22
> the log file is not helpful-- what would be helpful is a zipped QC report showing the vertebral labeling ran on the subjects

Do you refer to the both zipped QC folders in the #2 ?

**Comment by jcohenadad** [comment] 2024-05-31 17:39
> Do you refer to the both zipped QC folders in the https://github.com/Mathilde-16/STOP_MS_data/issues/2 ?

yes exactly

**Comment by Mathilde-16** [comment] 2024-06-09 12:09
This is the [zipped QC report](https://github.com/user-attachments/files/15751776/qc.zip) showing the vertebral labeling (and also the segmentation) ran on the subjects. And I've tried to assess it.

If you think that the SPINEPS method for the vertebral labeling is necessary, instead of manually labeling, could you provide assistance please ?

**Comment by jcohenadad** [comment] 2024-06-09 16:03
Here's my assessment of the QC report: [qc_flags.json](https://github.com/user-attachments/files/15753206/qc_flags.json)

Only a small proportion of the subjects failed vertebral labeling, so I think that running [manual correction](https://github.com/spinalcordtoolbox/manual-correction) will be more time effective. 

Tagging @NathanMolinier as this is relevant discussion/data for him

**Comment by Mathilde-16** [comment] 2024-06-09 20:18
Many thanks for your help !

**Comment by Mathilde-16** [comment] 2024-06-10 08:11
My apologies, I have an juste another about the vertebral labeling. 

In fact, according to your QC assessment there are only **5 subjects** which failed vertebral labeling, so not a lot as you said, but there are also **19 other subjects** which failed vertebral labeling (but not visible in the QC) because when I run the script, no output files are created for the vertebral labeling. Therefore, it failed for **24 subjects** in total. Sorry I didn't tell you this information about the 19 other subjects.
So do you think even with 24 subjects it will be more time effective to do it manually ?

**Comment by jcohenadad** [comment] 2024-06-10 13:45
Yes, doing it manually will be more time effective. It usually takes about 10s per subject to do 5 labels, so 24 subjects will be 240s --> 4min. Make sure to save the output labels in your derivative folder for reproducibility.

**Comment by Mathilde-16** [comment] 2024-06-10 16:45
Ok thank you.

My apologies again, I've had a discussion with my team so we have further details and one question.
First (the question😊), just to be sure, it's possible to do the manual correction or the Spineps method, even on subjects which failed because no output files are created for the vertebral labeling ? 

Moreover, our goal will be to apply this script on all subjects of the dataset, so it means 8 000 subjects. Currently, I'm processing the pipeline on 72 subjects only, and 24 have failed vertebral labeling so 33%. And we are in trouble because running manual correction on about 33% of 8 000 subjects will be not very fast... What do you think about it ? 
Sincerely sorry for asking you the same question again ! It's just because of the additional information.

**Comment by jcohenadad** [comment] 2024-06-10 17:48
> My apologies again, I've had a discussion with my team so we have further details and one question.
First (the question😊), just to be sure, it's possible to do the manual correction or the Spineps method, even on subjects which failed because no output files are created for the vertebral labeling ?

What you've used is `sct_label_vertebrae`, not SPINEPS. And what I'm suggesting is to _not_ run either of them but simply do this entire step manually (it takes about the same time to perform QC than to do the manual labelling, so there is no point in doing both, especially if the automatic procedure is often failing). 

> Moreover, our goal will be to apply this script on all subjects of the dataset, so it means 8 000 subjects. Currently, I'm processing the pipeline on 72 subjects only, and 24 have failed vertebral labeling so 33%. And we are in trouble because running manual correction on about 33% of 8 000 subjects will be not very fast... What do you think about it ?
Sincerely sorry for asking you the same question again ! It's just because of the additional information.

Ah! 8000 subjects is another beast indeed. For this, we will need an automatic and robust method to rely on. So, we need to spend more time on the selection of contrast that you use to do your labeling on. What are ALL the contrasts available in your dataset? Even the localizer could be useful. Maybe sending us a few representative subjects would be useful. We could then select the best strategy for automatic labeling. Tagging @NathanMolinier who will help with this

**Comment by NathanMolinier** [comment] 2024-06-10 18:39
To perform automatic discs labeling with SPINEPS, please follow this [guide](https://github.com/ivadomed/utilities/blob/main/quick_start_guides/use_SPINEPS_for_discs_labeling.md). If you meet any issues feel free to tag me, I will try to respond as quick as possible.

SPINEPS has weights for T2w scans and T1w scans

**Comment by Mathilde-16** [comment] 2024-06-10 20:36
> What you've used is `sct_label_vertebrae`, not SPINEPS. And what I'm suggesting is to _not_ run either of them but simply do this entire step manually (it takes about the same time to perform QC than to do the manual labelling, so there is no point in doing both, especially if the automatic procedure is often failing).

Okay, I understand what you mean.

> Ah! 8000 subjects is another beast indeed. For this, we will need an automatic and robust method to rely on. So, we need to spend more time on the selection of contrast that you use to do your labeling on. What are ALL the contrasts available in your dataset? Even the localizer could be useful. Maybe sending us a few representative subjects would be useful. We could then select the best strategy for automatic labeling. Tagging @NathanMolinier who will help with this

Thank you very much for your advice. I’m going to talk it over with my team and I’ll get back to you with further details.

**Comment by Mathilde-16** [comment] 2024-06-10 20:44
> To perform automatic discs labeling with SPINEPS, please follow this [guide](https://github.com/ivadomed/utilities/blob/main/quick_start_guides/use_SPINEPS_for_discs_labeling.md). If you meet any issues feel free to tag me, I will try to respond as quick as possible.
> 
> SPINEPS has weights for T2w scans and T1w scans

Many thanks for providing us assistance ! 
So I'm going to follow and rely on this SPINEPS guide.

**Comment by Mathilde-16** [comment] 2024-06-11 16:22
Hi ! I've the green light from Tobias Granberg to send you two representative subjects. @NathanMolinier could you please give me your e-mail address so that I can include you in the mail ? 

I think we only have T1 (MPRAGE and FLAIR) in the whole dataset but I need to check with my team. So regarding contrast and also the localizer, I´ll get back to you as soon as possible.
Thank you !

**Comment by NathanMolinier** [comment] 2024-06-11 17:08
My email is nathan.molinier@polymtl.ca

**Comment by Mathilde-16** [comment] 2024-06-11 17:47
> My email is [nathan.molinier@polymtl.ca](mailto:nathan.molinier@polymtl.ca)

Thank you !

Files are too heavy even if they are compressed, so do you think I can send them to you thanks to [WeTransfer](https://wetransfer.com/?source=codeur-com-blog&utm_source=codeur-com-blog) ? I ask this due to the fact they correspond to confidential data so I don't know if it's safe to send them thanks to a website

**Comment by jcohenadad** [comment] 2024-06-11 19:10
> so do you think I can send them to you thanks to [WeTransfer](https://wetransfer.com/?source=codeur-com-blog&utm_source=codeur-com-blog) ?

Email is equally problematic. What you can do is zip-encrypt, send via wetransfer, dropbox, gdrive or whatever, and send the password through email.

**Comment by Mathilde-16** [comment] 2024-06-12 10:13
Hi @NathanMolinier, 
Sorry I've a question regarding SPINEPS. Indeed, as I have a MacBook, CUDA is not available on my computer and it doesn't have a GPU NVIDIA. But I saw that SPINEPS only works with GPU so I did some research and a solution I found is to use Google Colab to have a GPU. 
What would you advise me to do?

**Comment by NathanMolinier** [comment] 2024-06-12 13:33
Actually now SPINEPS also works with CPU ! I have to update that sorry, but it will take longer to process.

I updated the README:

To run SPINEPS with cpu you need to comment the gpu line and uncomment the cpu line in the code block at the end of my README:

```bash
# Run SPINEPS on image with GPU
spineps sample -i "$tmp_img_path" -model_semantic "$semantic" -model_instance inst_vertebra_3.0 -dn derivatives
# Run SPINEPS on image with CPU
# spineps sample -i "$tmp_img_path" -model_semantic "$semantic" -model_instance inst_vertebra_3.0 -dn derivatives -cpu
```

**Comment by Mathilde-16** [comment] 2024-06-12 15:32
Perfect, thank you !

**Comment by Mathilde-16** [comment] 2024-06-12 16:43
Perfect, thank you !

I thought I had successfully installed SPINEPS but when I ran "_spineps -h_", my output terminal was as below : 

<img width="1087" alt="Screenshot 2024-06-12 at 18 25 53" src="https://github.com/Mathilde-16/STOP_MS_data/assets/161383359/5451bd70-5448-463f-931b-4d569337fb82">


So I guess this means that I didn't install SPINEPS correctly, isn't it ? 
I'm referring to the line "_AssertionError: Environment variable 'SPINEPS_SEGMENTOR_MODELS' = /Users/mathilde/spineps/spineps/models does not exist_"

**Comment by Mathilde-16** [comment] 2024-06-12 17:03
Hi @jcohenadad, 
I've some news from Russell regarding the contrasts : the majority of our dataset is with T1 but we have additional contrats too.
I copy/paste Russell's explanations below to provide all the details : 
"_We have additional contrasts (T2-w FLAIR and T2-w across most of all of the sessions, however, the majority will have only cerebral coverage, unlikely to have SC-C3/4 coverage, and more likely to only have up to C1.
We're in the process of sorting and QCing the images from the entire dataset now, but I would estimate that the proportion of the dataset that has up to T1/T2 C3/4 coverage would be about 20%, whereas the proportion with T1 C3/4 coverage would be about 70% of the 8000_."

**Comment by jcohenadad** [comment] 2024-06-12 17:08
> I've some news from Russell regarding the contrasts : the majority of our dataset is with T1 but we have additional contrats too.

How about localizers? All sessions should have that

**Comment by NathanMolinier** [comment] 2024-06-12 17:53
> So I guess this means that I didn't install SPINEPS correctly, isn't it ? I'm referring to the line "_AssertionError: Environment variable 'SPINEPS_SEGMENTOR_MODELS' = /Users/mathilde/spineps/spineps/models does not exist_"

It looks like you are at the step `7.` in my [guide](https://github.com/ivadomed/utilities/blob/main/quick_start_guides/use_SPINEPS_for_discs_labeling.md) you need now to run this command or add the line to your `.bashrc` or `.zshrc`: 

> Run this command or add it directly to your `.bashrc` or `.zshrc` (generally at the root of your home folder)
```bash
export SPINEPS_SEGMENTOR_MODELS=<PATH-to-SPINEPS>/spineps/models
```

Be careful about the path you provide to point to your clone of SPINEPS' github folder:
The path `Users/mathilde/spineps/spineps/models` does not seem to exist

**Comment by Mathilde-16** [comment] 2024-06-13 14:59
> > I've some news from Russell regarding the contrasts : the majority of our dataset is with T1 but we have additional contrats too.
> 
> How about localizers? All sessions should have that

Russell has just told me, that indeed, they should definitely have localizers. He doesn't have them isolated but he can dig into it and see if we have them. For this, He would like to know if you want localizers as a nifti ? 

Moreover, Russell tells me that he can send you more subjects (about 10) from our dataset, if it's more beneficial and useful.

**Comment by jcohenadad** [comment] 2024-06-13 17:15
yup, let’s see if loca helps with this task

**Comment by Mathilde-16** [comment] 2024-06-13 20:18
> yup, let’s see if loca helps with this task

Okay, I'll get back to you as soon as we have them.

**Comment by Mathilde-16** [comment] 2024-06-13 20:34
> Be careful about the path you provide to point to your clone of SPINEPS' github folder: The path `Users/mathilde/spineps/spineps/models` does not seem to exist

Thank you. I thought I had finished the installation but, indeed, I provided a wrong path. But now it's good, the path Users/mathilde/spineps/spineps/models exists. 

Regarding the **_label_with_spineps_** function, does the input image have to be the segmented one ?

**Comment by NathanMolinier** [comment] 2024-06-14 13:18
No you just need to provide the path to a given MRI scan:

## Usage

You can now call this function:
```bash
label_with_spineps "$IMG_PATH" "$OUT_PATH" "$CONTRAST"
```
With:
- `IMG_PATH` corresponding to the path to your input image
- `OUT_PATH` corresponding to the discs labels output path
- `CONTRAST` corresponding to the input contrast (`t1` or `t2`)

**Comment by Mathilde-16** [comment] 2024-06-17 10:35
Hi @NathanMolinier, I've added my [script](https://github.com/Mathilde-16/STOP_MS_data/blob/85742646242e19ebcccfef88e2e1d61571c25c61/Data_processing/SPINEPS_Vertebral_labeling/Script_SPINEPS.sh) with the label_with_spineps function in the STOP_MS_data repository. I tried to run this script on some subject sessions, but there are issues in the log files that I can't solve. 
Do you think it would be possible for you to look at my work please ? [Here's](https://github.com/user-attachments/files/15865660/Script_SPINEPS_sub-Control01_ses-aera01.log) one of my log files.

And I don't understand why in the log files there's still the issue about "_Environment variable 'SPINEPS_SEGMENTOR_MODELS' = /Users/mathilde/spineps/spineps/models does not exist_", indeed I did all the installation steps and when I run "spineps -h" in my terminal, this issue doesn't appear : 
<img width="1619" alt="Screenshot 2024-06-17 at 12 30 38" src="https://github.com/Mathilde-16/STOP_MS_data/assets/161383359/eb295c30-2e7c-4cd0-aac1-2de1f84048e1">
But in log files, there's still this issue...

Sorry!

**Comment by NathanMolinier** [comment] 2024-06-17 13:42
Hi @Mathilde-16, I just took a look at your log file and found this:

```
assert folder_path.exists(), f"Environment variable 'SPINEPS_SEGMENTOR_MODELS' = {folder_path} does not exist"
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: Environment variable 'SPINEPS_SEGMENTOR_MODELS' = Users/mathilde/spineps/spineps/models does not exist
```

So it looks like the problem is still the same. I don't know about the path you provided, but I believe you may have forgotten to add a `/` at the beginning of this path. The script is therefore looking for a `relative path` whereas you wanted to specify a `full path`:

Try with this path `/Users/mathilde/spineps/spineps/models`

**Comment by Mathilde-16** [comment] 2024-06-19 10:52
> So it looks like the problem is still the same. I don't know about the path you provided, but I believe you may have forgotten to add a / at the beginning of this path. The script is therefore looking for a relative path whereas you wanted to specify a full path

Now, this problem is solved, thank you.

Unfortunately, other issues persist in my log files, I tried to solve them in different ways but it still doesn't work. And I even tried re installing SPINEPS.
First, if I've understood correctly, a **"*_seg-vert_msk.nii.gz "** is supposed to be created in a temporary directory by launching label_with_spineps function. But I have the following line in my log files which means it doesn't work :  Expected output file not found: /var/folders/1q/6vxfb5k57tjdzgdv6zv49t6m0000gn/T/tmp.meRASHKm/derivatives//*_seg-vert_msk.nii.gz

Moreover, there is the following error : FileNotFoundError: [Errno 2] No such file or directory: '/Users/mathilde/spineps/spineps/models/T1w_Segmentor/fold_0/checkpoint_best.pth'
So I tried to re download the T1w_Segmentor zip in order to check, there is a checkpoint_final.pth file but no **checkpoint_best.pth** file in fold_0 (as in fold_1 and fold_2). Therefore, I really don't understand what the checkpoint_best.pth file is...

**Comment by NathanMolinier** [comment] 2024-06-19 14:12
I'm currently rerunning the different steps on my MacOS laptop to reproduce your errors ! Regarding the different problems you mentioned:

> Expected output file not found: /var/folders/1q/6vxfb5k57tjdzgdv6zv49t6m0000gn/T/tmp.meRASHKm/derivatives//*_seg-vert_msk.nii.gz

I'm not completely sure but I believe this issue is generated by zshell (default shell on MacOS): Path extensions are not handled the same way between zshell and bash so maybe you should try to add as a first line of your shell script: `#!/bin/bash`.

> [Errno 2] No such file or directory: '/Users/mathilde/spineps/spineps/models/T1w_Segmentor/fold_0/checkpoint_best.pth'

Regarding this error, I will try to reproduce it to understand

**Comment by Mathilde-16** [comment] 2024-06-19 15:20
> Regarding this error, I will try to reproduce it to understand

Thank you very much for your assistance and for taking time to do this !
I'm going to change the first line of my shell script

**Comment by NathanMolinier** [comment] 2024-06-19 16:58
I managed to reproduce the errors but it actually looks like multiple issues were generated in the last commits of spineps. I am currently submitting a [Pull Request](https://github.com/Hendrik-code/spineps/pull/22) to fix one main issue.

To make sure that it solved all your problems, could you run this:
- cd SPINEPS-FOLDER
- `git pull`
- `git checkout nm/fix_cpu_use`

And rerun your script

**Comment by NathanMolinier** [comment] 2024-06-19 18:09
The code was already merged to main, so you actually just need to pull the changes.

**Comment by Mathilde-16** [comment] 2024-06-19 18:41
> cd SPINEPS-FOLDER
git pull
git checkout nm/fix_cpu_use

Yes I did it by running these 3 commands (with **cd /Users/mathilde/spineps** for the first command).  
And I've just tried to rerun script several times but it still doesn't work. The problem with the checkpoint_best.pth file seems to be solved but regarding the "*_seg-vert_msk.nii.gz " file it's the same problem I'm sorry...

[Here's](https://github.com/user-attachments/files/15904814/Script_SPINEPS_1_sub-Control01_ses-aera01.log) one of my log files if you want to look at the errors

**Comment by NathanMolinier** [comment] 2024-06-19 18:59
Could you checkout back to the main branch ? 

By running `git checkout main` with a `git pull`

Then update the package TPTbox by running:
- `conda activate spineps`
- `pip install -U TPTBox`

And rerun ?

> The error with the path "*_seg-vert_msk.nii.gz " is actually happening because SPINEPS is failing

**Comment by Mathilde-16** [comment] 2024-06-19 20:17
> Could you checkout back to the main branch ?
> 
> By running git checkout main with a git pull
> 
> Then update the package TPTbox by running:
> 
> conda activate spineps
> pip install -U TPTBox

I did these steps and then, I've just tried to rerun script several times but it still doesn't work, sorry !
([new log file](https://github.com/user-attachments/files/15905547/Script_SPINEPS_1_sub-Control01_ses-aera01.log))

> The error with the path "*_seg-vert_msk.nii.gz " is actually happening because SPINEPS is failing

But if SPINEPS is still failing it's normal it doesn't work when I run the script, no ?

**Comment by NathanMolinier** [comment] 2024-06-20 13:44
The error you get is this one:

<img width="685" alt="Screenshot 2024-06-20 at 09 37 26" src="https://github.com/Mathilde-16/STOP_MS_data/assets/68945192/6adf3b1b-e017-4beb-b822-be5e80640d72">

SPINEPS has a lot constraints when it comes to naming files... But we are closer than ever ! Do you mind if I create an issue on SPINEPS with this screenshot ? I feel like this behaviour should not stop the execution.

> But if SPINEPS is still failing it's normal it doesn't work when I run the script, no ?

The function I wrote is basically calling spineps then calling another function to extract the discs labels from spineps' prediction. But if spineps fails the second function in my script is still called and it also generates an error due to the missing prediction.

**Comment by Mathilde-16** [comment] 2024-06-20 14:52
> SPINEPS has a lot constraints when it comes to naming files... But we are closer than ever ! Do you mind if I create an issue on SPINEPS with this screenshot ? I feel like this behaviour should not stop the execution.

Sure, you can! You're right, it will certainly help us. 😊

> The function I wrote is basically calling spineps then calling another function to extract the discs labels from spineps' prediction. But if spineps fails the second function in my script is still called and it also generates an error due to the missing prediction.

Ok thank you, now I understand better.

**Comment by NathanMolinier** [comment] 2024-06-20 15:07
I created an issue [here](https://github.com/Hendrik-code/spineps/issues/24)

**Comment by NathanMolinier** [comment] 2024-06-20 19:36
Hi @Mathilde-16,

Could you add the flag `-iic` to the spineps call ? Like this:
```
# Run SPINEPS on image with CPU
spineps sample -i "$tmp_img_path" -model_semantic "$semantic" -model_instance inst_vertebra_3.0 -dn derivatives -cpu -iic
```

**Comment by Mathilde-16** [comment] 2024-06-20 21:02
Hi @NathanMolinier, 
First, thank you for creating an issue !

> Could you add the flag -iic to the spineps call ? Like this:

Yes sure, I'm going to do it  and rerun my script now and I'll get back to you after.

**Comment by Mathilde-16** [comment] 2024-06-20 21:53
The script running is still ongoing, it's taking much longer than usual. Maybe that means it works ! I'll be in touch...



Finally it doesn't work unfortunately... But the log files generated show that progress has been made ! 
[Here's](https://github.com/user-attachments/files/15920930/Script_SPINEPS_1_sub-Control01_ses-aera01.log) one of these log files. So now, it looks like it doesn't work due to the "Vert Mask creation" which failed : 

<img width="1057" alt="Screenshot 2024-06-21 at 01 13 57" src="https://github.com/Mathilde-16/STOP_MS_data/assets/161383359/c534fa10-22e5-47a3-9aa2-237cabf667dc">

**Comment by jcohenadad** [comment] 2024-06-21 02:07
> it's taking much longer than usual. Maybe that means it works !

ahah yeah, that's usually a good assumption 😅

**Comment by NathanMolinier** [comment] 2024-06-21 13:49
Yes this is the type of problem that I won't be able to solve unfortunately. When spineps' prediction fails the discs labels won't be generated. I think we should be able to skip the subject if the prediction fails.

**Comment by Mathilde-16** [comment] 2024-06-21 14:36
> Yes this is the type of problem that I won't be able to solve unfortunately. When spineps' prediction fails the discs labels won't be generated.

Of course, I understand. 

> I think we should be able to skip the subject if the prediction fails.

I apologize, I don’t understand what you mean by skip the subject ?

**Comment by jcohenadad** [comment] 2024-06-21 15:26
> I apologize, I don’t understand what you mean by skip the subject ?

He meant that the discs should be manually identified for this subject. As I said in the beginning, it is possible that running SPINEPS and doing a thorough QC will actually be more time consuming than doing the disc labeling fully manually. By experience, it takes about 10s per subject to do disc labeling.

**Comment by Mathilde-16** [comment] 2024-06-21 16:36
Yes of course, I remembered. 
Thank you for your help !

**Comment by Mathilde-16** [comment] 2024-06-26 14:12
Hi @jcohenadad, 
As you recommended, instead of using SPINEPS, we are going to do the disc labeling manually, but just to be sure, when you said "fully manually" it means doing the disc labeling not only on subjects which failed but on ALL subjects of our dataset, isn't it ? And it also means we should not use the sct_label_vertebrae command at all ? 

We would also like to know, please, if you have a docker container for the most recent version of SCT ? And also if there is some SCT nomenclature for launching the batch processing script to run jobs in parallel ?
This way we can more swiftly process the dataset (first we would like to process 4,470 T1-w acquisitions and then the rest of the subjects).

**Comment by jcohenadad** [comment] 2024-06-26 14:46
> As you recommended, instead of using SPINEPS, we are going to do the disc labeling manually, but just to be sure, when you said "fully manually" it means doing the disc labeling not only on subjects which failed but on ALL subjects of our dataset, isn't it ? And it also means we should not use the sct_label_vertebrae command at all ?

correct.

> We would also like to know, please, if you have a docker container for the most recent version of SCT ?

we do not maintain SCT docker containers, but you can create one yourself very easily (ie: create container, download SCT, run the installer, save container). Tagging @joshuacwnewton in case he has additional tips for you.

> And also if there is some SCT nomenclature for launching the batch processing script to run jobs in parallel ?

what do you mean by 'nomenclature'? If you meant documentation, then yes, there is: https://spinalcordtoolbox.com/user_section/command-line.html#sct-run-batch. Also look at the latest SCT course, we show how to use this command. Also see this recent [project](https://github.com/sct-pipeline/spine-park?tab=readme-ov-file#perform-manual-vertebral-labeling), with video tutorial on how to do labeling.

> This way we can more swiftly process the dataset (first we would like to process 4,470 T1-w acquisitions and then the rest of the subjects).

Geeze! 4,470 subjects!!! In that case maybe it would be more strategic to wait a few weeks for @NathanMolinier to come up with another labeling strategy (he is working on a few promising approaches, esp. if the data are acquired with similar acq. parameters). In the long run it will be faster. Maybe you can send us a few representative subjects and we can see what is possible to do in a few weeks. @NathanMolinier what do you think?

**Comment by joshuacwnewton** [comment] 2024-06-26 20:32
> > We would also like to know, please, if you have a docker container for the most recent version of SCT ?
> 
> we do not maintain SCT docker containers, but you can create one yourself very easily (ie: create container, download SCT, run the installer, save container). Tagging @joshuacwnewton in case he has additional tips for you.

We have a set of Docker installation instructions here: [Linux](https://spinalcordtoolbox.com/user_section/installation/linux.html#option-4-install-with-docker), [macOS](https://spinalcordtoolbox.com/user_section/installation/mac.html#option-4-install-with-docker), [Windows](https://spinalcordtoolbox.com/user_section/installation/windows.html#docker-installation). These instructions were [recently rewritten](https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4196) thanks to @co-decode ( hooray! :tada: ), so they should be up to date. :)

**Comment by Mathilde-16** [comment] 2024-06-27 12:19
Thank you so much for all your recommendations and tips ! 
I'm going to talk it over with my team.

**Comment by Mathilde-16** [comment] 2024-06-28 21:56
Hello ! Since yesterday, we didn't have time to talk about all that yet with my team. Therefore in the meantime, I’m trying to install SCT with Docker, @joshuacwnewton😊. There’s a failure but I’m going to explain you this in the SCT forum just in case it's useful for the community.

**Comment by joshuacwnewton** [comment] 2024-06-28 22:23
Thank you so much for creating a forum post! That's perfect. And, answered! :hearts: 

(For reference, I'll just link the post and its response here: https://forum.spinalcordmri.org/t/issue-to-install-sct-with-docker-on-mac/1281/2)

**Comment by Mathilde-16** [comment] 2024-07-03 08:58
> Geeze! 4,470 subjects!!! In that case maybe it would be more strategic to wait a few weeks for @NathanMolinier to come up with another labeling strategy (he is working on a few promising approaches, esp. if the data are acquired with similar acq. parameters). In the long run it will be faster. Maybe you can send us a few representative subjects and we can see what is possible to do in a few weeks. @NathanMolinier what do you think?

Hello @jcohenadad, my apologies for the delate of the reply. Russell will send you a few representative subjects (about 20 subjects) by the end of the week. Thanks for your help.

**Comment by jcohenadad** [comment] 2024-07-23 17:03
Somewhat fixed by https://github.com/Mathilde-16/STOP_MS_data/pull/21

**Closed as completed by jcohenadad** 2024-07-23 17:03 UTC
